repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        entry: .venv/bin/ruff check --fix
        types: [python]
      - id: ruff-format
        name: ruff-format
        language: system
        entry: .venv/bin/ruff format
        types: [python]
